-- MySQL Script generated by MySQL Workbench
-- Sat Aug 22 22:26:54 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cookit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cookit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cookit` DEFAULT CHARACTER SET utf8 ;
USE `cookit` ;

-- -----------------------------------------------------
-- Table `cookit`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cookit`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `pass` VARCHAR(45) NULL,
  `avatar` VARCHAR(45) NULL,
  `rol` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `cp` VARCHAR(45) NULL,
  `localidad` VARCHAR(45) NULL,
  `provincia` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cookit`.`wines`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cookit`.`wines` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(200) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cookit`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cookit`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `idWine` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idWine_idx` (`idWine` ASC),
  CONSTRAINT `idWine`
    FOREIGN KEY (`idWine`)
    REFERENCES `cookit`.`wines` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cookit`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cookit`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `precio` DECIMAL(4,2) NULL,
  `descuento` SMALLINT(2) NULL,
  `descripcion` VARCHAR(200) NULL,
  `tiempo` SMALLINT(3) NULL,
  `apto` VARCHAR(100) NULL,
  `porciones` SMALLINT(2) NULL,
  `calorias` SMALLINT(3) NULL,
  `imagenes` VARCHAR(200) NULL,
  `receta` VARCHAR(45) NULL,
  `idCategorie` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idCategorie_idx` (`idCategorie` ASC),
  CONSTRAINT `idCategorie`
    FOREIGN KEY (`idCategorie`)
    REFERENCES `cookit`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cookit`.`carts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cookit`.`carts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idUser` INT NULL,
  `idProduct` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `idProduct_idx` (`idProduct` ASC),
  INDEX `idUser_idx` (`idUser` ASC),
  CONSTRAINT `idUser`
    FOREIGN KEY (`idUser`)
    REFERENCES `cookit`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProduct`
    FOREIGN KEY (`idProduct`)
    REFERENCES `cookit`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
